Config Files: update functionList per v7.9.1
notepad-plus-plus/npp-usermanual pull request #124
Opened 2020-10-28 16:39 UTC by pryrt

Update the functionList section of the Config Files documentation to mention the folder with separate files for each language, and the central overrideMap.

2020-10-28 19:24 UTC, MAPJe71 requested changes

2020-10-28 19:24 UTC, MAPJe71 commented on content/docs/config-files.md
> +1. In the `<associationMap>` section of, you need to add a line like the following:
> ... section of, ...

Section of what?

2020-10-28 20:02 UTC, pryrt commented on content/docs/config-files.md
> +1. In the `<associationMap>` section of, you need to add a line like the following:
oops, fixed

2020-10-29 16:04 UTC, donho requested changes
Please consider the remarks.

2020-10-29 16:04 UTC, donho commented on content/docs/config-files.md
> +    where the `fn_udl_example` must match the `<association id>` from the association map.  The `displayName` sets what shows in the **Function List** window header.  The `...Expr` values are all def
For this sentence:
`where the `fn_udl_example` must match the `<association id>` from the association map.`
I would change it to:
`where the `fn_udl_example` for v7.9 and previous versions, it must match the `<association id>` from the association map; for v7.9.1 and later versions, feel free to name it as you want.`

2020-10-29 22:37 UTC, pryrt commented
@donho , I believe I have implemented the changes you requested.  Let me know if this is okay now.
Thanks.

2020-10-30 22:07 UTC, pryrt commented
@donho : sounds good to me.

2020-11-01 18:28 UTC, pryrt commented
replaced by @donho's PR #128

2020-11-01 18:28 UTC, closed without merging