Add documentation for NPPM_GETDOCUMENTFROMBUFFER.
notepad-plus-plus/npp-usermanual pull request #126
Opened 2020-10-31 12:45 UTC by Kered13

This is documentation for PR #9085 in the notepad-plus-plus repo.

2020-10-31 16:48 UTC, pryrt requested changes
please edit

2020-10-31 16:48 UTC, pryrt commented on content/docs/plugin-communication.md
> +
Please add a the `---` between your section and the next section to make it consistent with the rest of the document.

2020-11-01 02:45 UTC, donho commented
I will merge it (or reject it).

2020-11-01 03:00 UTC, donho commented
For the sake of security and stability, `Document` object should keep internal usage only.
This PR is rejected because #9085 is rejected.

2020-11-01 03:00 UTC, closed without merging